name: GitHub Actions Demo
on:
  push:
    branches:
      - 'main'
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      env:
        type: environment
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
      - run: |
          echo $EVENT_CONTEXT
      - run: |
          echo $GITHUB_REF
      - uses: actions/checkout@v3.3.0
      - run: |
          ls -alR
